spring.application.name=nutri-express

# Configuração de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nutriexpress
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Spring Data JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
